
include(FetchContent)
set(PROJECT_NAME ExternalProjects)
project (${PROJECT_NAME})

#CPM
#[[
file(
  DOWNLOAD
  https://github.com/cpm-cmake/CPM.cmake/releases/download/v0.40.2/CPM.cmake
  ${CMAKE_CURRENT_BINARY_DIR}/cmake/CPM.cmake
)
]]
file(MAKE_DIRECTORY ${CMAKE_CURRENT_BINARY_DIR}/cmake)
file(COPY_FILE ${CMAKE_CURRENT_SOURCE_DIR}/CPM.cmake ${CMAKE_CURRENT_BINARY_DIR}/cmake/CPM.cmake)
include(${CMAKE_CURRENT_BINARY_DIR}/cmake/CPM.cmake)







CPMAddPackage(
  NAME glm
  GIT_TAG 1.0.1
  GITHUB_REPOSITORY g-truc/glm
  OPTIONS
	"GLM_BUILD_LIBRARY ON"
        "BUILD_SHARED_LIBS OFF"
)

CPMAddPackage(
  NAME imgui
  VERSION 1.91.6-docking
  GITHUB_REPOSITORY ocornut/imgui
  DOWNLOAD_ONLY TRUE
)
file(GLOB IMGUI_SourceList "${imgui_SOURCE_DIR}/*.cpp")
add_library(IMGUI STATIC ${IMGUI_SourceList})
target_include_directories(IMGUI PUBLIC ${imgui_SOURCE_DIR})



CPMAddPackage(
  NAME assimp
  GIT_TAG v5.4.3
  GITHUB_REPOSITORY assimp/assimp
  OPTIONS
	"ASSIMP_WARNINGS_AS_ERRORS OFF"
	"ASSIMP_INJECT_DEBUG_POSTFIX OFF"
	"ASSIMP_INSTALL OFF"
	"ASSIMP_BUILD_TESTS OFF"
)


#slang

#[[
CPMAddPackage(
  NAME slang
  GIT_TAG master
  GITHUB_REPOSITORY A-RAVEN/slang
  GIT_SUBMODULES_RECURSE TRUE
  GIT_PROGRESS TRUE
  EXCLUDE_FROM_ALL TRUE
  OPTIONS
	"SLANG_SLANG_LLVM_FLAVOR DISABLE"
	"SLANG_LIB_TYPE STATIC"
	"SLANG_ENABLE_SLANG_GLSLANG ON"
	"SLANG_ENABLE_DXIL ON"
	"SLANG_ENABLE_TESTS OFF"
	"SLANG_ENABLE_GFX OFF"
	"SLANG_ENABLE_SLANGD OFF"
	"SLANG_ENABLE_SLANGRT OFF"
	"SLANG_ENABLE_EXAMPLES OFF"
)
]]

#[[
CPMAddPackage(
  NAME slang
  URL https://github.com/shader-slang/slang/releases/download/v2024.17/slang-2024.17-windows-x86_64.zip
  VERSION 2024.17
  # the range-v3 CMakeLists screws with configuration options
  DOWNLOAD_ONLY True
)
find_package(slang REQUIRED PATHS ${slang_SOURCE_DIR}/cmake NO_DEFAULT_PATH)
]]

#[[
CPMAddPackage(
  NAME slang
  GIT_TAG v2024.15.2
  GITHUB_REPOSITORY shader-slang/slang
  GIT_SUBMODULES_RECURSE TRUE
  GIT_PROGRESS TRUE
  EXCLUDE_FROM_ALL TRUE
  OPTIONS
	"SLANG_SLANG_LLVM_FLAVOR DISABLE"
	"SLANG_LIB_TYPE SHARED"
	"SLANG_ENABLE_SLANG_GLSLANG ON"
	"SLANG_ENABLE_DXIL ON"
	"SLANG_ENABLE_TESTS OFF"
	"SLANG_ENABLE_GFX OFF"
	"SLANG_ENABLE_SLANGD OFF"
	"SLANG_ENABLE_SLANGRT OFF"
	"SLANG_ENABLE_EXAMPLES OFF"
)
]]

#STB
if(NOT TARGET stb)
CPMAddPackage(
  NAME stb
  GIT_TAG master
  GITHUB_REPOSITORY nothings/stb
  DOWNLOAD_ONLY TRUE
)
add_library(stb INTERFACE)
target_include_directories(stb INTERFACE ${stb_SOURCE_DIR})
endif()

CPMAddPackage(
  NAME JoltPhysics
  VERSION 5.2.0
  GITHUB_REPOSITORY jrouwe/JoltPhysics
  SOURCE_SUBDIR Build
  EXCLUDE_FROM_ALL TRUE
  OPTIONS
	"CROSS_PLATFORM_DETERMINISTIC ON"
	"OVERRIDE_CXX_FLAGS OFF"
)



