#pragma once

#define CAPARENS ()
#define CAEXPAND(...) CAEXPAND4(CAEXPAND4(CAEXPAND4(CAEXPAND4(__VA_ARGS__))))
#define CAEXPAND4(...) CAEXPAND3(CAEXPAND3(CAEXPAND3(CAEXPAND3(__VA_ARGS__))))
#define CAEXPAND3(...) CAEXPAND2(CAEXPAND2(CAEXPAND2(CAEXPAND2(__VA_ARGS__))))
#define CAEXPAND2(...) CAEXPAND1(CAEXPAND1(CAEXPAND1(CAEXPAND1(__VA_ARGS__))))
#define CAEXPAND1(...) __VA_ARGS__